"""Approximate symmetry plane estimation for helmet meshes."""

from dataclasses import dataclass
from typing import Any

import numpy as np
from scipy.spatial import cKDTree
import trimesh

from app.config import DEFAULT_SYMMETRY_CONFIG, SymmetrySearchConfig


@dataclass(frozen=True)
class SymmetryResult:
    """Estimated symmetry plane for a helmet mesh."""

    plane_point: np.ndarray
    plane_normal: np.ndarray
    score: float
    sample_count: int
    search_config: dict[str, Any]
    normal: np.ndarray
    origin: np.ndarray
    status: str
    message: str


def reflect_points_across_plane(
    points: np.ndarray,
    plane_point: np.ndarray,
    plane_normal: np.ndarray,
) -> np.ndarray:
    """Reflect points across a plane defined by point and unit normal."""

    normal = _unit_vector(plane_normal)
    signed_distance = (points - plane_point) @ normal
    return points - 2.0 * signed_distance[:, np.newaxis] * normal


def score_symmetry_plane(
    points: np.ndarray,
    tree: cKDTree,
    plane_point: np.ndarray,
    plane_normal: np.ndarray,
    trim_ratio: float,
) -> float:
    """Score a candidate plane by mirrored nearest-neighbor distance."""

    reflected = reflect_points_across_plane(points, plane_point, plane_normal)
    distances, _ = tree.query(reflected, k=1)
    return _trimmed_mean(distances, trim_ratio)


def solve_symmetry_plane(
    mesh: trimesh.Trimesh,
    config: SymmetrySearchConfig = DEFAULT_SYMMETRY_CONFIG,
) -> SymmetryResult:
    """Search for the lowest-error symmetry plane near the YZ plane.

    The search assumes helmet symmetry is close to the YZ plane, so candidate
    normals are generated by rotating +X around Y and Z by small angles.
    """

    points = _sample_vertices(np.asarray(mesh.vertices, dtype=float), config.max_sample)
    if len(points) == 0:
        raise ValueError("Cannot solve symmetry plane for an empty mesh.")

    tree = cKDTree(points)
    center = points.mean(axis=0)
    extents = np.ptp(points, axis=0)
    offset_span = max(float(np.linalg.norm(extents)) * config.offset_ratio, 1e-9)

    best_score = float("inf")
    best_point = center.copy()
    best_normal = np.array([1.0, 0.0, 0.0], dtype=float)
    candidates = 0

    for normal in _candidate_normals(config.angle_range_deg, config.angle_step_deg):
        offsets = np.linspace(-offset_span, offset_span, config.offset_steps)
        for offset in offsets:
            point = center + normal * float(offset)
            score = score_symmetry_plane(
                points=points,
                tree=tree,
                plane_point=point,
                plane_normal=normal,
                trim_ratio=config.trim_ratio,
            )
            candidates += 1
            if score < best_score:
                best_score = score
                best_point = point
                best_normal = normal

    if best_normal[0] < 0.0:
        best_normal = -best_normal

    config_dict = {
        "max_sample": config.max_sample,
        "angle_range_deg": config.angle_range_deg,
        "angle_step_deg": config.angle_step_deg,
        "offset_ratio": config.offset_ratio,
        "offset_steps": config.offset_steps,
        "trim_ratio": config.trim_ratio,
        "candidate_count": candidates,
    }
    return SymmetryResult(
        plane_point=best_point,
        plane_normal=best_normal,
        score=float(best_score),
        sample_count=int(len(points)),
        search_config=config_dict,
        origin=best_point,
        normal=best_normal,
        status="completed",
        message=f"Solved approximate symmetry plane with score {best_score:.6g}.",
    )


def estimate_symmetry_plane(
    mesh: trimesh.Trimesh,
    config: SymmetrySearchConfig = DEFAULT_SYMMETRY_CONFIG,
) -> SymmetryResult:
    """Estimate the helmet symmetry plane."""

    return solve_symmetry_plane(mesh, config)


def _sample_vertices(vertices: np.ndarray, max_sample: int) -> np.ndarray:
    """Return a deterministic subset of mesh vertices."""

    if max_sample <= 0:
        raise ValueError("max_sample must be positive.")
    if len(vertices) <= max_sample:
        return vertices.copy()
    indices = np.linspace(0, len(vertices) - 1, max_sample, dtype=int)
    return vertices[indices]


def _candidate_normals(angle_range_deg: float, angle_step_deg: float) -> list[np.ndarray]:
    """Generate +X-like candidate normals by rotating around Y and Z."""

    if angle_step_deg <= 0:
        raise ValueError("angle_step_deg must be positive.")

    angles = np.arange(
        -angle_range_deg,
        angle_range_deg + angle_step_deg * 0.5,
        angle_step_deg,
        dtype=float,
    )
    normals: list[np.ndarray] = []
    for y_deg in angles:
        y_rad = np.deg2rad(y_deg)
        rotation_y = np.array(
            [
                [np.cos(y_rad), 0.0, np.sin(y_rad)],
                [0.0, 1.0, 0.0],
                [-np.sin(y_rad), 0.0, np.cos(y_rad)],
            ],
            dtype=float,
        )
        for z_deg in angles:
            z_rad = np.deg2rad(z_deg)
            rotation_z = np.array(
                [
                    [np.cos(z_rad), -np.sin(z_rad), 0.0],
                    [np.sin(z_rad), np.cos(z_rad), 0.0],
                    [0.0, 0.0, 1.0],
                ],
                dtype=float,
            )
            normals.append(_unit_vector(rotation_z @ rotation_y @ np.array([1.0, 0.0, 0.0])))
    return normals


def _trimmed_mean(values: np.ndarray, trim_ratio: float) -> float:
    """Return mean after dropping the largest trim ratio of values."""

    if len(values) == 0:
        return float("inf")
    sorted_values = np.sort(values)
    keep_count = int(np.ceil(len(sorted_values) * (1.0 - trim_ratio)))
    keep_count = max(1, min(keep_count, len(sorted_values)))
    return float(np.mean(sorted_values[:keep_count]))


def _unit_vector(vector: np.ndarray) -> np.ndarray:
    """Normalize a vector and reject degenerate input."""

    norm = float(np.linalg.norm(vector))
    if norm <= 1e-12:
        raise ValueError("Cannot normalize a zero-length vector.")
    return np.asarray(vector, dtype=float) / norm
